<a href="https://colab.research.google.com/github/sairamharshith/AMERICANEXPRESSDATAANALYSIS/blob/main/CODE/AMERICANEXPRESSDATAANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DEEP LEARNING VIA ANN

## IMPORTING LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.2'

## IMPORTING DATASET

In [ ]:
data_set = pd.read_csv('CREDIT.csv')
x = data_set.iloc[0:9927, :-1].values
y = data_set.iloc[0:9927, -1].values


In [ ]:
print(x)

[[553.0 'Delhi' 'Female' ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 'Male' ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 'Female' ... 4.0 1.0 545501.0]
 ...
 [627.0 'Mumbai' 'Female' ... 4.0 0.0 494067.0]
 [600.0 'Bengaluru' 'Female' ... 2.0 1.0 109375.0]
 [553.0 'Delhi' 'Male' ... 4.0 1.0 180031.0]]


In [ ]:
print(y)

[0. 0. 0. ... 0. 1. 0.]


## ENCODING CATEGORICAL DATA

### GENDER COLUMN: LABELENCODING

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [ ]:
print(x)

[[553.0 'Delhi' 0 ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 1 ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 0 ... 4.0 1.0 545501.0]
 ...
 [627.0 'Mumbai' 0 ... 4.0 0.0 494067.0]
 [600.0 'Bengaluru' 0 ... 2.0 1.0 109375.0]
 [553.0 'Delhi' 1 ... 4.0 1.0 180031.0]]


### GEOGRAPHY COLUMN: ONEHOTENCODING

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [0.0 0.0 1.0 ... 4.0 0.0 494067.0]
 [1.0 0.0 0.0 ... 2.0 1.0 109375.0]
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]]


## SPLITTING INTO TRAIN AND TEST DATASETS

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 ... 4.0 1.0 264201.0]
 [0.0 0.0 1.0 ... 4.0 1.0 328575.0]
 [1.0 0.0 0.0 ... 2.0 0.0 168958.0]
 ...
 [0.0 0.0 1.0 ... 2.0 1.0 248115.0]
 [0.0 0.0 1.0 ... 2.0 1.0 499155.0]
 [1.0 0.0 0.0 ... 2.0 0.0 10454.0]]


In [ ]:
print(y_train)

[0. 0. 0. ... 1. 1. 0.]


## FEATURE SCALING

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -0.06854301]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
   0.34018176]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.67326188]
 ...
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
  -0.17067658]
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.4232319 ]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -1.67963883]]


In [ ]:
print(x_test)

[[-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.44738434]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
  -1.23191715]
 [ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -1.72970878]
 ...
 [ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857 -1.53641095
   0.12692412]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.59717281]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175    0.65086753
   1.67285788]]


# ANN

## INITIALIZATION

In [ ]:
ann = tf.keras.models.Sequential()

## ADDING INPUT LAYER AND FIRST HIDDEN LAYER 

In [ ]:
ann.add(tf.keras.layers.Dense(units =6, activation = 'relu'))

## ADDING SECOND HIDDEN LAYER

In [ ]:
ann.add(tf.keras.layers.Dense(units =6, activation = 'relu'))

## ADDING OUTPUT LAYER

In [ ]:
ann.add(tf.keras.layers.Dense(units =1, activation = 'sigmoid'))

# ANN TRAINING

## ANN COMPILING

In [ ]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = ['accuracy'] )

## TRAINING ON TRAINING DATASET

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs= 120)

Epoch 1/120
249/249 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7757
Epoch 2/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4699 - accuracy: 0.7965
Epoch 3/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4548 - accuracy: 0.7964
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4466 - accuracy: 0.7957
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4411 - accuracy: 0.7968
Epoch 6/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.8007
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4345 - accuracy: 0.7993
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4321 - accuracy: 0.8005
Epoch 9/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 0.8036
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4282 - accura

# PREDICTIONS

## SINGLE PREDICTION

In [ ]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]]))> 0.5)

[[False]]


## PREDICTION ON TESTSET

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0. 1.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 1.]
 [0. 0.]
 [1. 1.]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[1514   59]
 [ 220  193]]


0.8595166163141994